### ISSUE TITLE
multi-GPU

### ISSUE THREAD

**Issue by cmhungsteve** [fungtion/DSN#1]
Did you try to make it work on multi gpus?
I tried to modified your codes for multi-gpu, but it always give me this error:

``RuntimeError: arguments are located on different GPUs``

Did you meet this issue? and how did you deal with that?
Thank you!

**Comment by fungtion** [comment]
I ran this code on a single GPU and have not yet ran it on multi-gpu. Can your modification methods work well on other codes?  Can you show me where is this error comes from in my code?
