### ISSUE TITLE
Question about ReverseLayerF

### ISSUE THREAD

**Issue by Lucksong** [fungtion/DSN#6]
Hi, it is very cool for your code, but I don't understand the 'ReverseLayerF.apply(shared_code,p)' you used in model_compat.py, what role does it play? 
Thanks!

**Comment by fungtion** [comment]
@Lucksong forward broadcast using static function.

**Comment by chenyonx** [comment]
Have you run through the program yet?Do you know where to download the data set?

**Comment by fungtion** [comment]
@ chenyonx you can find the dataset [here](https://github.com/fungtion/DANN)

**Comment by chenyonx** [comment]
OK，thank you，it's successful。
